name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build (TypeScript + Vite)
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Show coverage
        uses: davelosert/vitest-coverage-report-action@v2
